export interface Package {
  id: string
  name: string
  amount: string
  price: string
  serviceId?: string
  min?: number
  max?: number
  avgTime?: string
  features?: string[]
  category: 'follower' | 'like' | 'view' | 'engagement' | 'other'
}

export interface Service {
  id: string
  name: string
  description: string
  icon: string
  packages: Package[]
}

// SMM Turk API'den seçilen en iyi hizmetler
export const servicesData: Service[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    description: 'Yabancı takipçi satın al hizmetiyle Instagram hesabınızı büyütün, etkileşiminizi artırın. Güvenilir ve hızlı çözümler için A Social Media\'yı tercih edin.',
    icon: '📷',
    packages: [
      {
        id: '9403',
        name: 'Instagram Takipçi [ 30 Gün Garantili ]',
        amount: '100 - 1.000.000 Takipçi',
        price: '533₺ / 1K',
        serviceId: '9403',
        min: 100,
        max: 1000000,
        avgTime: '55 dakika',
        features: ['30 Gün Garantili ♻️', 'Hızlı Başlangıç', 'Telafi Butonu Aktif', '%100 Eski Hesaplar'],
        category: 'follower',
      },
      {
        id: '9320',
        name: 'Instagram Premium Türk Takipçi [ 365 Gün Garantili ]',
        amount: '50 - 1.000.000 Takipçi',
        price: '4.834₺ / 1K',
        serviceId: '9320',
        min: 50,
        max: 1000000,
        avgTime: '2 saat 5 dakika',
        features: ['365 Gün Telafili ♻️', '%100 Türk', 'Saatte 10K', 'Max 100K'],
        category: 'follower',
      },
      {
        id: '9209',
        name: 'Instagram Premium Takipçi [ 99 Gün Garantili ]',
        amount: '100 - 1.000.000 Takipçi',
        price: '504₺ / 1K',
        serviceId: '9209',
        min: 100,
        max: 1000000,
        avgTime: '48 saat',
        features: ['99 Gün Telafili ♻️', 'Eski Hesaplar', 'Günlük Hız: 100K'],
        category: 'follower',
      },
      {
        id: '9397',
        name: 'Instagram Beğeni [ 30 Gün Garantili ]',
        amount: '50 - 1.000.000 Beğeni',
        price: '71₺ / 1K',
        serviceId: '9397',
        min: 50,
        max: 1000000,
        avgTime: '6 saat 7 dakika',
        features: ['30 Gün Garantili ♻️', '%100 Eski Hesaplar', 'Maksimum 100K'],
        category: 'like',
      },
      {
        id: '9336',
        name: 'Instagram Video İzlenme',
        amount: '100 - 2.000.000 İzlenme',
        price: '4₺ / 1K',
        serviceId: '9336',
        min: 100,
        max: 2000000,
        avgTime: '1 saat 46 dakika',
        features: ['Anlık Başlar', 'Erişim + Gösterim', 'Günlük 500K'],
        category: 'view',
      },
      {
        id: '9337',
        name: 'Instagram Hikaye İzlenme',
        amount: '50 - 30.000 İzlenme',
        price: '39₺ / 1K',
        serviceId: '9337',
        min: 50,
        max: 30000,
        avgTime: '6 saat 56 dakika',
        features: ['%100 Eski Hesaplar', 'Hızlı', 'Maksimum 30K'],
        category: 'view',
      },
      {
        id: '9335',
        name: 'Instagram Türk Repost',
        amount: '10 - 500 Repost',
        price: '38.084₺ / 1K',
        serviceId: '9335',
        min: 10,
        max: 500,
        avgTime: '12 saat 22 dakika',
        features: ['%100 Gerçek Türk 🇹🇷', 'Hızlı Başlar', 'Maksimum 500'],
        category: 'engagement',
      },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    description: 'Facebook hesabınızı büyütün ve etkileşiminizi artırın. Güvenilir ve hızlı çözümler için A Social Media\'yı tercih edin.',
    icon: '👥',
    packages: [
      {
        id: '9010',
        name: 'Facebook Sayfa Takipçi [ 30 Gün Garantili ]',
        amount: '100 - 5.000.000 Takipçi',
        price: '407₺ / 1K',
        serviceId: '9010',
        min: 100,
        max: 5000000,
        avgTime: '2 saat 3 dakika',
        features: ['30 Gün Garantili ♻️', '%100 Global Kullanıcılar', 'Anlık Başlar', 'Doğal Artar'],
        category: 'follower',
      },
      {
        id: '9011',
        name: 'Facebook Profil Takipçi [ 30 Gün Garantili ]',
        amount: '100 - 5.000.000 Takipçi',
        price: '359₺ / 1K',
        serviceId: '9011',
        min: 100,
        max: 5000000,
        avgTime: '2 saat 36 dakika',
        features: ['30 Gün Garantili ♻️', '%100 Global Kullanıcılar', 'Anlık Başlar', 'Doğal Artar'],
        category: 'follower',
      },
      {
        id: '9313',
        name: 'Facebook Sayfa/Profil Takipçi [Global] [ 30 Gün Garantili ]',
        amount: '10 - 100.000 Takipçi',
        price: '302₺ / 1K',
        serviceId: '9313',
        min: 10,
        max: 100000,
        avgTime: '5 dakika',
        features: ['30 Gün Telafili ♻️', 'Global Kullanıcılar', 'Günlük 20K-30K'],
        category: 'follower',
      },
      {
        id: '2815',
        name: 'Facebook Yabancı Sayfa Beğeni [ 30 Gün Garantili ]',
        amount: '10 - 1.000.000 Beğeni',
        price: '678₺ / 1K',
        serviceId: '2815',
        min: 10,
        max: 1000000,
        avgTime: '0 - 1 saat',
        features: ['30 Gün Telafi ♻️', 'Yabancı Kullanıcılar', 'Maksimum 100K'],
        category: 'like',
      },
      {
        id: '7651',
        name: 'Facebook Yabancı Sayfa Beğeni',
        amount: '10 - 50.000 Beğeni',
        price: '310₺ / 1K',
        serviceId: '7651',
        min: 10,
        max: 50000,
        avgTime: '45 dakika',
        features: ['Yabancı Kullanıcılar', 'Maksimum 100K', 'Hızlı Başlangıç'],
        category: 'like',
      },
      {
        id: '3852',
        name: 'Facebook Gönderi Beğeni',
        amount: '100 - 10.000.000 Beğeni',
        price: '275₺ / 1K',
        serviceId: '3852',
        min: 100,
        max: 10000000,
        avgTime: '0 - 2 saat',
        features: ['Maksimum 40K', 'Hızlı Teslimat'],
        category: 'like',
      },
      {
        id: '3947',
        name: 'Facebook %100 Türk Gönderi Beğeni',
        amount: '10 - 25.000 Beğeni',
        price: '2.568₺ / 1K',
        serviceId: '3947',
        min: 10,
        max: 25000,
        avgTime: '0 - 2 saat',
        features: ['%100 Türk 🇹🇷', 'Maksimum 5K', 'Yüksek Kalite'],
        category: 'like',
      },
      {
        id: '2664',
        name: 'Facebook Profil Takipçi',
        amount: '100 - 5.000.000 Takipçi',
        price: '443₺ / 1K',
        serviceId: '2664',
        min: 100,
        max: 5000000,
        avgTime: '0 - 2 saat',
        features: ['Maksimum 200K', 'Hızlı Başlangıç'],
        category: 'follower',
      },
      {
        id: '1972',
        name: 'Facebook Canlı Yayın İzlenme [ 30 Dakika ]',
        amount: '20 - 50.000 İzlenme',
        price: '431₺ / 1K',
        serviceId: '1972',
        min: 20,
        max: 50000,
        avgTime: '0 - 20 dakika',
        features: ['Canlı Yayın', '30 Dakika Yayında Kalır'],
        category: 'view',
      },
      {
        id: '2919',
        name: 'Facebook Canlı Yayın İzlenme [ 60 Dakika ]',
        amount: '20 - 50.000 İzlenme',
        price: '862₺ / 1K',
        serviceId: '2919',
        min: 20,
        max: 50000,
        avgTime: '0 - 20 dakika',
        features: ['Canlı Yayın', '60 Dakika Yayında Kalır'],
        category: 'view',
      },
      {
        id: '3672',
        name: 'Facebook Türk Gerçek Yorum [ 100 Adet ]',
        amount: '1 Adet',
        price: '2.700₺',
        serviceId: '3672',
        min: 1,
        max: 1,
        avgTime: '0 - 2 saat',
        features: ['%100 Türk 🇹🇷', 'Gerçek Yorumlar', '100 Adet'],
        category: 'engagement',
      },
      {
        id: '8971',
        name: 'Facebook Sayfa Beğeni + Takipçi [ 30 Gün Garantili ]',
        amount: '10 - 1.000.000',
        price: '271₺ / 1K',
        serviceId: '8971',
        min: 10,
        max: 1000000,
        avgTime: '17 dakika',
        features: ['30 Gün Garantili ♻️', '%100 Global Kullanıcılar', 'Anlık Başlar', 'Doğal Artar'],
        category: 'engagement',
      },
      {
        id: '6857',
        name: 'Facebook Etkileşim Paketi [Premium]',
        amount: '5 - 1.000 Adet',
        price: '21.000₺ / 1K',
        serviceId: '6857',
        min: 5,
        max: 1000,
        avgTime: '0 - 2 saat',
        features: ['Premium Paket', 'Yüksek Kalite', 'Kapsamlı Etkileşim'],
        category: 'engagement',
      },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'YouTube kanalınızı büyütün ve videolarınızın izlenme sayısını artırın. Güvenilir ve hızlı çözümler için A Social Media\'yı tercih edin.',
    icon: '▶️',
    packages: [
      {
        id: '9414',
        name: 'YouTube Abone [ 30 Gün Garantili ]',
        amount: '50 - 30.000 Abone',
        price: '9.892₺ / 1K',
        serviceId: '9414',
        min: 50,
        max: 30000,
        avgTime: '31 saat 57 dakika',
        features: ['30 Gün Garantili ♻️', 'Günlük 100-300', 'Daha Az Düşüş'],
        category: 'follower',
      },
      {
        id: '9415',
        name: 'YouTube Abone [ Hızlı | 30 Gün Garantili ]',
        amount: '50 - 50.000 Abone',
        price: '12.320₺ / 1K',
        serviceId: '9415',
        min: 50,
        max: 50000,
        avgTime: 'Yeni Hizmet',
        features: ['30 Gün Garantili ♻️', 'Günlük Hız 300-500', 'Hızlı Başlangıç'],
        category: 'follower',
      },
      {
        id: '8495',
        name: 'YouTube Abone [ Ömür Boyu Telafi ]',
        amount: '100 - 1.000.000 Abone',
        price: '10.490₺ / 1K',
        serviceId: '8495',
        min: 100,
        max: 1000000,
        avgTime: 'Yeni Hizmet',
        features: ['Ömür Boyu Telafi ♻️', 'Günlük Hız 5K', 'Maksimum 300K'],
        category: 'follower',
      },
      {
        id: '8498',
        name: 'YouTube Abone [ Ömür Boyu Telafi | Hızlı ]',
        amount: '100 - 100.000 Abone',
        price: '12.239₺ / 1K',
        serviceId: '8498',
        min: 100,
        max: 100000,
        avgTime: 'Yeni Hizmet',
        features: ['Ömür Boyu Telafi ♻️', 'Günlük Hız 30K', 'Maksimum 100K'],
        category: 'follower',
      },
      {
        id: '3431',
        name: 'YouTube Abone [ Ömür Boyu Telafi ]',
        amount: '100 - 1.000.000 Abone',
        price: '12.983₺ / 1K',
        serviceId: '3431',
        min: 100,
        max: 1000000,
        avgTime: '48 saat',
        features: ['Ömür Boyu Telafi ♻️', 'Günlük Hız 5K', 'Maksimum 300K'],
        category: 'follower',
      },
      {
        id: '3430',
        name: 'YouTube %100 Türk Abone',
        amount: '100 - 1.000.000 Abone',
        price: '21.686₺ / 1K',
        serviceId: '3430',
        min: 100,
        max: 1000000,
        avgTime: '48 saat',
        features: ['%100 Türk 🇹🇷', 'Maksimum 2K', 'Düşüş Yok'],
        category: 'follower',
      },
      {
        id: '9411',
        name: 'YouTube İzlenme Saatleri [ 60 Dakikalık Video ]',
        amount: '5 - 4.000 Saat',
        price: '12.782₺ / 1K',
        serviceId: '9411',
        min: 5,
        max: 4000,
        avgTime: '9 saat 32 dakika',
        features: ['30 Gün Garantili ♻️', 'Günlük 100-200', '60 Dakikalık Video'],
        category: 'view',
      },
      {
        id: '9031',
        name: 'YouTube İzlenme Saati [ Ömür Boyu Garantili | 5 DK Video ]',
        amount: '100 - 10.000 Saat',
        price: '6.219₺ / 1K',
        serviceId: '9031',
        min: 100,
        max: 10000,
        avgTime: '82 saat 10 dakika',
        features: ['Ömür Boyu Garantili ♻️', 'Düşüş Yok', '5 Dakikalık Video', 'Hız 500/Saat'],
        category: 'view',
      },
      {
        id: '9034',
        name: 'YouTube İzlenme Saati [ Ömür Boyu Garantili | 60 DK Video ]',
        amount: '100 - 100.000 Saat',
        price: '12.968₺ / 1K',
        serviceId: '9034',
        min: 100,
        max: 100000,
        avgTime: 'Yeni Hizmet',
        features: ['Ömür Boyu Garantili ♻️', 'Düşüş Yok', '60 Dakikalık Video', 'Hız 500/Saat'],
        category: 'view',
      },
      {
        id: '8102',
        name: 'YouTube Gerçek İzlenme [ Ömür Boyu Telafi ]',
        amount: '100 - 10.000.000 İzlenme',
        price: '389₺ / 1K',
        serviceId: '8102',
        min: 100,
        max: 10000000,
        avgTime: '12 saat',
        features: ['Ömür Boyu Telafi ♻️', 'Günlük Hız 20K', 'Maksimum 1M'],
        category: 'view',
      },
      {
        id: '9160',
        name: 'YouTube İzlenme [ Ömür Boyu Garantili ]',
        amount: '100 - 1.000.000 İzlenme',
        price: '633₺ / 1K',
        serviceId: '9160',
        min: 100,
        max: 1000000,
        avgTime: '7 saat 35 dakika',
        features: ['Ömür Boyu Garantili ♻️', 'Günlük Hız 40K/50K'],
        category: 'view',
      },
      {
        id: '9203',
        name: 'YouTube İzlenme [ 365 Gün Garantili ]',
        amount: '100 - 10.000.000 İzlenme',
        price: '571₺ / 1K',
        serviceId: '9203',
        min: 100,
        max: 10000000,
        avgTime: 'Yeni Hizmet',
        features: ['365 Gün Garantili ♻️', 'Günlük Hız 40K/50K'],
        category: 'view',
      },
      {
        id: '7024',
        name: 'YouTube Shorts İzlenme [ Ömür Boyu Garantili ]',
        amount: '100 - 10.000.000 İzlenme',
        price: '577₺ / 1K',
        serviceId: '7024',
        min: 100,
        max: 10000000,
        avgTime: '48 saat',
        features: ['Ömür Boyu Garantili ♻️', 'Günlük Hız 20K/30K', 'Shorts'],
        category: 'view',
      },
      {
        id: '7272',
        name: 'YouTube Beğeni',
        amount: '10 - 100.000 Beğeni',
        price: '62₺ / 1K',
        serviceId: '7272',
        min: 10,
        max: 100000,
        avgTime: 'Yeni Hizmet',
        features: ['Günlük Hız: 50K', 'Maksimum 100K', 'Hızlı Başlangıç'],
        category: 'like',
      },
      {
        id: '9322',
        name: 'YouTube Beğeni [ 30 Gün Telafili ]',
        amount: '10 - 75.000 Beğeni',
        price: '546₺ / 1K',
        serviceId: '9322',
        min: 10,
        max: 75000,
        avgTime: '3 dakika',
        features: ['30 Gün Telafili ♻️', 'Maksimum 50K', 'Günlük Hız 3-5K'],
        category: 'like',
      },
      {
        id: '4048',
        name: 'YouTube Türk Beğeni [ 30 Gün Telafi ]',
        amount: '10 - 60.000 Beğeni',
        price: '884₺ / 1K',
        serviceId: '4048',
        min: 10,
        max: 60000,
        avgTime: '0 - 12 saat',
        features: ['%100 Türk 🇹🇷', '30 Gün Telafi ♻️', 'Maksimum 40K'],
        category: 'like',
      },
      {
        id: '7017',
        name: 'YouTube Shorts Beğeni [ 30 Gün Telafi ]',
        amount: '100 - 300.000 Beğeni',
        price: '303₺ / 1K',
        serviceId: '7017',
        min: 100,
        max: 300000,
        avgTime: '0 - 12 saat',
        features: ['30 Gün Telafi ♻️', 'Maksimum 300K', 'Shorts'],
        category: 'like',
      },
      {
        id: '3432',
        name: 'YouTube İzlenme + Beğeni [ 60 Gün Garantili ]',
        amount: '100 - 10.000.000',
        price: '462₺ / 1K',
        serviceId: '3432',
        min: 100,
        max: 10000000,
        avgTime: '48 saat',
        features: ['60 Gün Garantili ♻️', 'Günlük Hız 20K/60K', '2\'li Paket'],
        category: 'engagement',
      },
      {
        id: '7271',
        name: 'YouTube İzlenme + Beğeni [ Ömür Boyu Garantili ]',
        amount: '100 - 10.000.000',
        price: '577₺ / 1K',
        serviceId: '7271',
        min: 100,
        max: 10000000,
        avgTime: '48 saat',
        features: ['Ömür Boyu Garantili ♻️', 'Günlük Hız 5K/10K', '2\'li Paket'],
        category: 'engagement',
      },
      {
        id: '9373',
        name: 'YouTube Hype Boost [ Yeni Keşfet Sistemi ]',
        amount: '1 - 1.000',
        price: '221.000₺ / 1K',
        serviceId: '9373',
        min: 1,
        max: 1000,
        avgTime: '48 saat',
        features: ['Yeni Keşfet Sistemi', 'Maksimum 1K', 'Premium'],
        category: 'engagement',
      },
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    description: 'TikTok hesabınızı büyütün ve videolarınızın etkileşimini artırın. Güvenilir ve hızlı çözümler için subjective\'ı tercih edin.',
    icon: '🎵',
    packages: [
      {
        id: '9391',
        name: 'TikTok Takipçi [ 30 Gün Garantili ]',
        amount: '10 - 1.000.000 Takipçi',
        price: '802₺ / 1K',
        serviceId: '9391',
        min: 10,
        max: 1000000,
        avgTime: '7 dakika',
        features: ['30 Gün Garantili ♻️', 'Yüksek Kaliteli ve Gerçek Hesaplar', 'Günlük 100K'],
        category: 'follower',
      },
      {
        id: '9390',
        name: 'TikTok Takipçi [ 15 Gün Garantili ]',
        amount: '10 - 1.000.000 Takipçi',
        price: '771₺ / 1K',
        serviceId: '9390',
        min: 10,
        max: 1000000,
        avgTime: '35 dakika',
        features: ['15 Gün Garantili ♻️', 'Yüksek Kaliteli ve Gerçek Hesaplar', 'Günlük 100K'],
        category: 'follower',
      },
      {
        id: '9309',
        name: 'TikTok Takipçi [ Hızlı | 30 Gün Garantili ]',
        amount: '50 - 1.000.000 Takipçi',
        price: '776₺ / 1K',
        serviceId: '9309',
        min: 50,
        max: 1000000,
        avgTime: '5 dakika',
        features: ['30 Gün Telafili ♻️', 'Günlük 100K 🚀', 'Ultra Hız'],
        category: 'follower',
      },
      {
        id: '9317',
        name: 'TikTok Takipçi [ Hızlı | 30 Gün Garantili ]',
        amount: '50 - 1.000.000 Takipçi',
        price: '1.171₺ / 1K',
        serviceId: '9317',
        min: 50,
        max: 1000000,
        avgTime: '56 saat 51 dakika',
        features: ['30 Gün Garantili ♻️', 'Günlük 100K 🚀', 'Premium Kalite'],
        category: 'follower',
      },
      {
        id: '8189',
        name: 'TikTok Takipçi [ %100 Organik ]',
        amount: '100 - 100.000 Takipçi',
        price: '976₺ / 1K',
        serviceId: '8189',
        min: 100,
        max: 100000,
        avgTime: '5 dakika',
        features: ['%100 Organik', 'Gerçek Global Kullanıcılar', 'Günde 100-200'],
        category: 'follower',
      },
      {
        id: '9395',
        name: 'TikTok Beğeni [ 30 Gün Garantili ]',
        amount: '10 - 10.000.000 Beğeni',
        price: '103₺ / 1K',
        serviceId: '9395',
        min: 10,
        max: 10000000,
        avgTime: '31 dakika',
        features: ['30 Gün Garantili ♻️', 'Yüksek Kaliteli ve Gerçek Profiller', 'Günlük 100K'],
        category: 'like',
      },
      {
        id: '9394',
        name: 'TikTok Beğeni',
        amount: '10 - 10.000.000 Beğeni',
        price: '74₺ / 1K',
        serviceId: '9394',
        min: 10,
        max: 10000000,
        avgTime: '1 saat 25 dakika',
        features: ['Maksimum 10M', 'Günlük 100K', 'Hızlı Başlangıç'],
        category: 'like',
      },
      {
        id: '4019',
        name: 'TikTok Beğeni [ Orta Kalite ]',
        amount: '10 - 1.000.000 Beğeni',
        price: '21₺ / 1K',
        serviceId: '4019',
        min: 10,
        max: 1000000,
        avgTime: '3 dakika',
        features: ['Maksimum 250K', 'Orta Kalite', 'Günlük 10K'],
        category: 'like',
      },
      {
        id: '8247',
        name: 'TikTok Türk Beğeni',
        amount: '10 - 20.000 Beğeni',
        price: '490₺ / 1K',
        serviceId: '8247',
        min: 10,
        max: 20000,
        avgTime: '3 dakika',
        features: ['🇹🇷 Türk', 'Maksimum 20K', 'Süper Hızlı', 'Günlük 20K'],
        category: 'like',
      },
      {
        id: '9393',
        name: 'TikTok Video İzlenme',
        amount: '100 - 1.000.000.000 İzlenme',
        price: '4₺ / 1K',
        serviceId: '9393',
        min: 100,
        max: 1000000000,
        avgTime: '46 dakika',
        features: ['Sınırsız Maksimum Kapasite', 'Hızlı Başlangıç', 'Günlük 10M'],
        category: 'view',
      },
      {
        id: '2766',
        name: 'TikTok Video İzlenme [ Anlık Başlar ]',
        amount: '50 - 2.147.483.647 İzlenme',
        price: '1₺ / 1K',
        serviceId: '2766',
        min: 50,
        max: 2147483647,
        avgTime: '30 dakika',
        features: ['Anlık Başlar', '1M/Günlük Hız', 'Sınırsız'],
        category: 'view',
      },
      {
        id: '9025',
        name: 'TikTok Video İzlenme [ Ömür Boyu Telafi ]',
        amount: '50 - 2.147.483.647 İzlenme',
        price: '2₺ / 1K',
        serviceId: '9025',
        min: 50,
        max: 2147483647,
        avgTime: 'Yeni Hizmet',
        features: ['Ömür Boyu Telafi ♻️', 'Anlık Başlar', '1M/Günlük Hız'],
        category: 'view',
      },
      {
        id: '4319',
        name: 'TikTok Video İzlenme [ Maksimum 50M ]',
        amount: '50 - 2.147.483.647 İzlenme',
        price: '1₺ / 1K',
        serviceId: '4319',
        min: 50,
        max: 2147483647,
        avgTime: '20 dakika',
        features: ['Maksimum 50M', 'Hızlı Başlangıç'],
        category: 'view',
      },
      {
        id: '9006',
        name: 'TikTok İzlenme + Kaydetme + Paylaşım',
        amount: '100 - 10.000.000',
        price: '5₺ / 1K',
        serviceId: '9006',
        min: 100,
        max: 10000000,
        avgTime: '40 dakika',
        features: ['3\'lü Paket', 'Maksimum 2M', 'Kapsamlı Etkileşim'],
        category: 'engagement',
      },
      {
        id: '8379',
        name: 'TikTok PK Battle Points',
        amount: '100 - 2.147.483.647 Points',
        price: '154₺ / 1K',
        serviceId: '8379',
        min: 100,
        max: 2147483647,
        avgTime: '1 dakika',
        features: ['Anlık Başlar', '100M/Günlük Hız', 'PK Battle'],
        category: 'engagement',
      },
      {
        id: '5965',
        name: 'TikTok Kadın Etkileşim Paketi [ 5 Adet ]',
        amount: '1 Adet',
        price: '450₺',
        serviceId: '5965',
        min: 1,
        max: 1,
        avgTime: '1 saat 14 dakika',
        features: ['Kadın Kullanıcılar', 'İzle + Beğen + Yorum', '5 Adet'],
        category: 'engagement',
      },
      {
        id: '5971',
        name: 'TikTok Erkek Etkileşim Paketi [ 5 Adet ]',
        amount: '1 Adet',
        price: '450₺',
        serviceId: '5971',
        min: 1,
        max: 1,
        avgTime: '1 saat 44 dakika',
        features: ['Erkek Kullanıcılar', 'İzle + Beğen + Yorum', '5 Adet'],
        category: 'engagement',
      },
    ],
  },
  {
    id: 'twitter',
    name: 'Twitter (X)',
    description: 'Twitter hesabınızı büyütün ve tweetlerinizin etkileşimini artırın. Güvenilir ve hızlı çözümler için A Social Media\'yı tercih edin.',
    icon: '🐦',
    packages: [
      {
        id: '9342',
        name: 'Twitter Takipçi [ 30 Gün Garantili ]',
        amount: '100 - 50.000 Takipçi',
        price: '3.374₺ / 1K',
        serviceId: '9342',
        min: 100,
        max: 50000,
        avgTime: '15 saat 53 dakika',
        features: ['30 Gün Garantili ♻️', 'Yüksek Kaliteli Kullanıcılar', 'Günlük 10K'],
        category: 'follower',
      },
      {
        id: '9344',
        name: 'Twitter Takipçi [ 90 Gün Garantili ]',
        amount: '100 - 50.000 Takipçi',
        price: '5.653₺ / 1K',
        serviceId: '9344',
        min: 100,
        max: 50000,
        avgTime: '1 saat 9 dakika',
        features: ['90 Gün Garantili ♻️', 'Yüksek Kaliteli Kullanıcılar', 'Günlük 20K'],
        category: 'follower',
      },
      {
        id: '9293',
        name: 'Twitter Türk Tweet Görüntülenme',
        amount: '100 - 50.000.000 Görüntülenme',
        price: '99₺ / 1K',
        serviceId: '9293',
        min: 100,
        max: 50000000,
        avgTime: '2 dakika',
        features: ['%100 Türk 🇹🇷', 'Anlık Başlar', 'Maksimum 50M'],
        category: 'view',
      },
      {
        id: '9263',
        name: 'Twitter Latin Takipçi [ 90 Gün Garantili ]',
        amount: '10 - 10.000 Takipçi',
        price: '7.554₺ / 1K',
        serviceId: '9263',
        min: 10,
        max: 10000,
        avgTime: 'Yeni Hizmet',
        features: ['90 Gün Telafili ♻️', 'Latin Ülkeler', 'Maksimum 100K'],
        category: 'follower',
      },
      {
        id: '9264',
        name: 'Twitter Latin Beğeni [ 30 Gün Garantili ]',
        amount: '10 - 10.000 Beğeni',
        price: '1.688₺ / 1K',
        serviceId: '9264',
        min: 10,
        max: 10000,
        avgTime: '1 saat 34 dakika',
        features: ['30 Gün Telafili ♻️', 'Latin Ülkeler', 'Maksimum 100K'],
        category: 'like',
      },
      {
        id: '9265',
        name: 'Twitter Latin Retweet [ 30 Gün Garantili ]',
        amount: '20 - 100.000 Retweet',
        price: '755₺ / 1K',
        serviceId: '9265',
        min: 20,
        max: 100000,
        avgTime: 'Yeni Hizmet',
        features: ['30 Gün Telafili ♻️', 'Latin Ülkeler', 'Maksimum 100K'],
        category: 'engagement',
      },
      {
        id: '9256',
        name: 'Twitter Organik Takipçi',
        amount: '5 - 2.000 Takipçi',
        price: '1.291₺ / 1K',
        serviceId: '9256',
        min: 5,
        max: 2000,
        avgTime: '13 saat 16 dakika',
        features: ['100% Organik', 'Maksimum 2K', 'Yüksek Kalite'],
        category: 'follower',
      },
      {
        id: '9257',
        name: 'Twitter Organik Retweet',
        amount: '1 - 2.000 Retweet',
        price: '1.453₺ / 1K',
        serviceId: '9257',
        min: 1,
        max: 2000,
        avgTime: '1 saat 14 dakika',
        features: ['100% Organik', 'Maksimum 2K', 'Yüksek Kalite'],
        category: 'engagement',
      },
      {
        id: '9258',
        name: 'Twitter Organik Beğeni',
        amount: '5 - 3.000 Beğeni',
        price: '1.217₺ / 1K',
        serviceId: '9258',
        min: 5,
        max: 3000,
        avgTime: '5 saat 2 dakika',
        features: ['100% Organik', 'Maksimum 3K', 'Günlük Hız 3K'],
        category: 'like',
      },
      {
        id: '9183',
        name: 'Twitter Canlı Yayın İzlenme [ 15 Dakika ]',
        amount: '50 - 200.000 İzlenme',
        price: '1.697₺ / 1K',
        serviceId: '9183',
        min: 50,
        max: 200000,
        avgTime: 'Yeni Hizmet',
        features: ['Canlı Yayın', '15 Dakika', 'Anlık Başlar'],
        category: 'view',
      },
      {
        id: '9184',
        name: 'Twitter Canlı Yayın İzlenme [ 30 Dakika ]',
        amount: '10 - 200.000 İzlenme',
        price: '3.393₺ / 1K',
        serviceId: '9184',
        min: 10,
        max: 200000,
        avgTime: 'Yeni Hizmet',
        features: ['Canlı Yayın', '30 Dakika', 'Anlık Başlar'],
        category: 'view',
      },
    ],
  },
]

// Paket fiyatlarını hesapla (1K fiyatından)
export function calculatePackagePrice(pricePer1K: string, amount: number): string {
  const numericPrice = parseFloat(pricePer1K.replace(/[^\d,]/g, '').replace(',', '.'))
  const totalPrice = (numericPrice * amount) / 1000
  return Math.round(totalPrice).toString() + '₺'
}

// Paket miktarlarını oluştur (min-max arası)
export function generatePackageAmounts(min: number, max: number): Array<{ amount: number; price: string }> {
  const amounts: number[] = []
  
  // Küçük paketler
  if (min <= 50) amounts.push(50)
  if (min <= 100) amounts.push(100)
  if (min <= 250) amounts.push(250)
  if (min <= 500) amounts.push(500)
  if (min <= 750) amounts.push(750)
  if (min <= 1000) amounts.push(1000)
  
  // Orta paketler
  if (min <= 2500 && max >= 2500) amounts.push(2500)
  if (min <= 5000 && max >= 5000) amounts.push(5000)
  if (min <= 7500 && max >= 7500) amounts.push(7500)
  if (min <= 10000 && max >= 10000) amounts.push(10000)
  
  // Büyük paketler
  if (min <= 25000 && max >= 25000) amounts.push(25000)
  if (min <= 50000 && max >= 50000) amounts.push(50000)
  if (min <= 75000 && max >= 75000) amounts.push(75000)
  if (min <= 100000 && max >= 100000) amounts.push(100000)
  if (min <= 250000 && max >= 250000) amounts.push(250000)
  if (min <= 500000 && max >= 500000) amounts.push(500000)
  if (min <= 1000000 && max >= 1000000) amounts.push(1000000)
  
  return amounts.filter(a => a >= min && a <= max).map(amount => ({
    amount,
    price: calculatePackagePrice('53,28₺ / 1K', amount), // Bu dinamik olmalı
  }))
}
