export interface Package {
  id: string
  name: string
  amount: string
  price: string
  serviceId?: string
  min?: number
  max?: number
  avgTime?: string
  features?: string[]
  category: 'follower' | 'like' | 'view' | 'engagement' | 'other'
}

export interface Service {
  id: string
  name: string
  description: string
  icon: string
  packages: Package[]
}

// SMM Turk API'den seçilen en iyi hizmetler
export const servicesData: Service[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    description: 'Yabancı takipçi satın al hizmetiyle Instagram hesabınızı büyütün, etkileşiminizi artırın. Güvenilir ve hızlı çözümler için subjective\'ı tercih edin.',
    icon: '📷',
    packages: [
      {
        id: '9403',
        name: 'Instagram Takipçi [ 30 Gün Garantili ]',
        amount: '100 - 1.000.000 Takipçi',
        price: '100₺ / 1K',
        serviceId: '9403',
        min: 100,
        max: 1000000,
        avgTime: '55 dakika',
        features: ['30 Gün Garantili ♻️', 'Hızlı Başlangıç', 'Telafi Butonu Aktif', '%100 Eski Hesaplar'],
        category: 'follower',
      },
      {
        id: '9209',
        name: 'Instagram Premium Takipçi [ 99 Gün Garantili ]',
        amount: '100 - 1.000.000 Takipçi',
        price: '700₺ / 1K',
        serviceId: '9209',
        min: 100,
        max: 1000000,
        avgTime: '48 saat',
        features: ['99 Gün Telafili ♻️', 'Eski Hesaplar', 'Günlük Hız: 100K'],
        category: 'follower',
      },
      {
        id: '9420',
        name: '🇹🇷 Instagram Türk Takipçi [ 90 Gün Telafili ]',
        amount: '100 - 2.500 Takipçi',
        price: '1800₺ / 1K',
        serviceId: '9420',
        min: 100,
        max: 2500,
        avgTime: '57 dakika',
        features: ['90 Gün Telafili ♻️', '%100 Türk 🇹🇷', 'Maksimum 30K', 'Günde 15K'],
        category: 'follower',
      },
      {
        id: '9421',
        name: '🇹🇷 Instagram Türk Kadın Takipçi [ 90 Gün Telafili ]',
        amount: '100 - 2.500 Takipçi',
        price: '1.900₺ / 1K',
        serviceId: '9421',
        min: 100,
        max: 2500,
        avgTime: '7 dakika',
        features: ['90 Gün Telafili ♻️', '%100 Türk Kadın 👩', 'Maksimum 30K', 'Günde 15K'],
        category: 'follower',
      },
      {
        id: '9397',
        name: 'Instagram Beğeni [ 30 Gün Garantili ]',
        amount: '50 - 1.000.000 Beğeni',
        price: '75₺ / 1K',
        serviceId: '9397',
        min: 50,
        max: 1000000,
        avgTime: '6 saat 7 dakika',
        features: ['30 Gün Garantili ♻️', '%100 Eski Hesaplar', 'Maksimum 100K'],
        category: 'like',
      },
      {
        id: '9336',
        name: 'Instagram Video İzlenme',
        amount: '100 - 2.000.000 İzlenme',
        price: '40₺ / 1K',
        serviceId: '9336',
        min: 100,
        max: 2000000,
        avgTime: '1 saat 46 dakika',
        features: ['Anlık Başlar', 'Erişim + Gösterim', 'Günlük 500K'],
        category: 'view',
      },
      {
        id: '9337',
        name: 'Instagram Hikaye İzlenme',
        amount: '500 - 30.000 İzlenme',
        price: '20₺ / 1K',
        serviceId: '9337',
        min: 500,
        max: 30000,
        avgTime: '6 saat 56 dakika',
        features: ['%100 Eski Hesaplar', 'Hızlı', 'Maksimum 30K'],
        category: 'view',
      },
      {
        id: '9335',
        name: 'Instagram Türk Repost',
        amount: '10 - 500 Repost',
        price: '40₺ / 1K',
        serviceId: '9335',
        min: 10,
        max: 500,
        avgTime: '12 saat 22 dakika',
        features: ['%100 Gerçek Türk 🇹🇷', 'Hızlı Başlar', 'Maksimum 500'],
        category: 'engagement',
      },
      {
        id: '5372',
        name: 'Instagram Premium Yorum [ 5 Adet ]',
        amount: '1 Adet',
        price: '30₺',
        serviceId: '5372',
        min: 1,
        max: 1,
        avgTime: '3 saat 10 dakika',
        features: ['Premium Paket', 'Son 9 Gönderiden En Az Yorum Olana Yorum', '5 Adet'],
        category: 'engagement',
      },
      {
        id: '5373',
        name: 'Instagram Premium Yorum [ 10 Adet ]',
        amount: '1 Adet',
        price: '50₺',
        serviceId: '5373',
        min: 1,
        max: 1,
        avgTime: '3 saat 20 dakika',
        features: ['Premium Paket', 'Son 9 Gönderiden En Az Yorum Olana Yorum', '10 Adet'],
        category: 'engagement',
      },
      {
        id: '5374',
        name: 'Instagram Premium Yorum [ 25 Adet ]',
        amount: '1 Adet',
        price: '125₺',
        serviceId: '5374',
        min: 1,
        max: 1,
        avgTime: '3 saat 22 dakika',
        features: ['Premium Paket', 'Son 9 Gönderiden En Az Yorum Olana Yorum', '25 Adet'],
        category: 'engagement',
      },
      {
        id: '5375',
        name: 'Instagram Premium Yorum [ 50 Adet ]',
        amount: '1 Adet',
        price: '250₺',
        serviceId: '5375',
        min: 1,
        max: 1,
        avgTime: '3 saat 30 dakika',
        features: ['Premium Paket', 'Son 9 Gönderiden En Az Yorum Olana Yorum', '50 Adet'],
        category: 'engagement',
      },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    description: 'Facebook hesabınızı büyütün ve etkileşiminizi artırın. Güvenilir ve hızlı çözümler için subjective\'ı tercih edin.',
    icon: '👥',
    packages: [
      {
        id: '9010',
        name: 'Facebook Sayfa Takipçi [ 30 Gün Garantili ]',
        amount: '100 - 5.000.000 Takipçi',
        price: '280₺ / 1K',
        serviceId: '9010',
        min: 100,
        max: 5000000,
        avgTime: '2 saat 3 dakika',
        features: ['30 Gün Garantili ♻️', '%100 Global Kullanıcılar', 'Anlık Başlar', 'Doğal Artar'],
        category: 'follower',
      },
      
      {
        id: '9313',
        name: 'Facebook Sayfa/Profil Takipçi [Global] [ 30 Gün Garantili ]',
        amount: '10 - 100.000 Takipçi',
        price: '100₺ / 1K',
        serviceId: '9313',
        min: 10,
        max: 100000,
        avgTime: '5 dakika',
        features: ['30 Gün Telafili ♻️', 'Global Kullanıcılar', 'Günlük 20K-30K'],
        category: 'follower',
      },
      
      {
        id: '3852',
        name: 'Facebook Gönderi Beğeni',
        amount: '100 - 10.000.000 Beğeni',
        price: '60₺ / 1K',
        serviceId: '3852',
        min: 100,
        max: 10000000,
        avgTime: '0 - 2 saat',
        features: ['Maksimum 40K', 'Hızlı Teslimat'],
        category: 'like',
      },
      {
        id: '3947',
        name: 'Facebook %100 Türk Gönderi Beğeni',
        amount: '10 - 25.000 Beğeni',
        price: '500₺ / 1K',
        serviceId: '3947',
        min: 10,
        max: 25000,
        avgTime: '0 - 2 saat',
        features: ['%100 Türk 🇹🇷', 'Maksimum 5K', 'Yüksek Kalite'],
        category: 'like',
      },
      
      {
        id: '1972',
        name: 'Facebook Canlı Yayın İzlenme [ 30 Dakika ]',
        amount: '20 - 50.000 İzlenme',
        price: '40₺ / 1K',
        serviceId: '1972',
        min: 20,
        max: 50000,
        avgTime: '0 - 20 dakika',
        features: ['Canlı Yayın', '30 Dakika Yayında Kalır'],
        category: 'view',
      },
      {
        id: '2919',
        name: 'Facebook Canlı Yayın İzlenme [ 60 Dakika ]',
        amount: '20 - 50.000 İzlenme',
        price: '200₺ / 1K',
        serviceId: '2919',
        min: 20,
        max: 50000,
        avgTime: '0 - 20 dakika',
        features: ['Canlı Yayın', '60 Dakika Yayında Kalır'],
        category: 'view',
      },
      {
        id: '3672',
        name: 'Facebook Türk Gerçek Yorum [ 100 Adet ]',
        amount: '1 Adet',
        price: '400₺',
        serviceId: '3672',
        min: 1,
        max: 1,
        avgTime: '0 - 2 saat',
        features: ['%100 Türk 🇹🇷', 'Gerçek Yorumlar', '100 Adet'],
        category: 'engagement',
      },
      
      
      {
        id: '6857',
        name: 'Facebook Etkileşim Paketi [Premium]',
        amount: '5 - 1.000 Adet',
        price: '2500₺ / 1K',
        serviceId: '6857',
        min: 5,
        max: 1000,
        avgTime: '0 - 2 saat',
        features: ['Premium Paket', 'Yüksek Kalite', 'Kapsamlı Etkileşim'],
        category: 'engagement',
      },
      {
        id: '3777-10',
        name: 'Facebook Değerlendirme [%100 Aktif Türk ] - 10 Adet',
        amount: '10 Değerlendirme',
        price: '175₺',
        serviceId: '3777',
        min: 10,
        max: 10,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Sayfa Değerlendirme', '10 Adet'],
        category: 'engagement',
      },
      {
        id: '3777-20',
        name: 'Facebook Değerlendirme [%100 Aktif Türk ] - 20 Adet',
        amount: '20 Değerlendirme',
        price: '250₺',
        serviceId: '3777',
        min: 20,
        max: 20,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Sayfa Değerlendirme', '20 Adet'],
        category: 'engagement',
      },
      {
        id: '3777-50',
        name: 'Facebook Değerlendirme [%100 Aktif Türk ] - 50 Adet [Kampanya]',
        amount: '50 Değerlendirme',
        price: '500₺',
        serviceId: '3777',
        min: 50,
        max: 50,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Sayfa Değerlendirme', '50 Adet', '🔥 Kampanya'],
        category: 'engagement',
      },
      {
        id: '3777-70',
        name: 'Facebook Değerlendirme [%100 Aktif Türk ] - 70 Adet',
        amount: '70 Değerlendirme',
        price: '700₺',
        serviceId: '3777',
        min: 70,
        max: 70,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Sayfa Değerlendirme', '70 Adet'],
        category: 'engagement',
      },
      {
        id: '3777-100',
        name: 'Facebook Değerlendirme [%100 Aktif Türk ] - 100 Adet [Kampanya]',
        amount: '100 Değerlendirme',
        price: '1000₺',
        serviceId: '3777',
        min: 100,
        max: 100,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Sayfa Değerlendirme', '100 Adet', '🔥 Kampanya'],
        category: 'engagement',
      },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'YouTube kanalınızı büyütün ve videolarınızın izlenme sayısını artırın. Güvenilir ve hızlı çözümler için subjective\'ı tercih edin.',
    icon: '▶️',
    packages: [
      
      {
        id: '9415',
        name: 'YouTube Abone [ Hızlı | 30 Gün Garantili ]',
        amount: '50 - 50.000 Abone',
        price: '3500₺ / 1K',
        serviceId: '9415',
        min: 50,
        max: 50000,
        avgTime: 'Yeni Hizmet',
        features: ['30 Gün Garantili ♻️', 'Günlük Hız 300-500', 'Hızlı Başlangıç'],
        category: 'follower',
      },
      
      {
        id: '3430',
        name: 'YouTube %100 Türk Abone',
        amount: '100 - 1.000.000 Abone',
        price: '3500₺ / 1K',
        serviceId: '3430',
        min: 100,
        max: 1000000,
        avgTime: '48 saat',
        features: ['%100 Türk 🇹🇷', 'Maksimum 2K', 'Düşüş Yok'],
        category: 'follower',
      },
      {
        id: '9411',
        name: 'YouTube İzlenme Saatleri [ 60 Dakikalık Video ]',
        amount: '5 - 4.000 Saat',
        price: '2.000₺ / 1K',
        serviceId: '9411',
        min: 5,
        max: 4000,
        avgTime: '9 saat 32 dakika',
        features: ['30 Gün Garantili ♻️', 'Günlük 100-200', '60 Dakikalık Video'],
        category: 'view',
      },
   
      {
        id: '9203',
        name: 'YouTube İzlenme [ 365 Gün Garantili ]',
        amount: '100 - 10.000.000 İzlenme',
        price: '150₺ / 1K',
        serviceId: '9203',
        min: 100,
        max: 10000000,
        avgTime: 'Yeni Hizmet',
        features: ['365 Gün Garantili ♻️', 'Günlük Hız 40K/50K'],
        category: 'view',
      },
      {
        id: '7024',
        name: 'YouTube Shorts İzlenme [ Ömür Boyu Garantili ]',
        amount: '100 - 10.000.000 İzlenme',
        price: '150₺ / 1K',
        serviceId: '7024',
        min: 100,
        max: 10000000,
        avgTime: '48 saat',
        features: ['Ömür Boyu Garantili ♻️', 'Günlük Hız 20K/30K', 'Shorts'],
        category: 'view',
      },
      {
        id: '7272',
        name: 'YouTube Beğeni',
        amount: '10 - 100.000 Beğeni',
        price: '99₺ / 1K',
        serviceId: '7272',
        min: 10,
        max: 100000,
        avgTime: 'Yeni Hizmet',
        features: ['Günlük Hız: 50K', 'Maksimum 100K', 'Hızlı Başlangıç'],
        category: 'like',
      },
      
      {
        id: '4048',
        name: 'YouTube Türk Beğeni [ 30 Gün Telafi ]',
        amount: '10 - 60.000 Beğeni',
        price: '150₺ / 1K',
        serviceId: '4048',
        min: 10,
        max: 60000,
        avgTime: '0 - 12 saat',
        features: ['%100 Türk 🇹🇷', '30 Gün Telafi ♻️', 'Maksimum 40K'],
        category: 'like',
      },
      {
        id: '7017',
        name: 'YouTube Shorts Beğeni [ 30 Gün Telafi ]',
        amount: '100 - 300.000 Beğeni',
        price: '50₺ / 1K',
        serviceId: '7017',
        min: 100,
        max: 300000,
        avgTime: '0 - 12 saat',
        features: ['30 Gün Telafi ♻️', 'Maksimum 300K', 'Shorts'],
        category: 'like',
      },
      {
        id: '3432',
        name: 'YouTube İzlenme + Beğeni [ 60 Gün Garantili ]',
        amount: '100 - 10.000.000',
        price: '250₺ / 1K',
        serviceId: '3432',
        min: 100,
        max: 10000000,
        avgTime: '48 saat',
        features: ['60 Gün Garantili ♻️', 'Günlük Hız 20K/60K', '2\'li Paket'],
        category: 'engagement',
      },
     
      
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    description: 'TikTok hesabınızı büyütün ve videolarınızın etkileşimini artırın. Güvenilir ve hızlı çözümler için subjective\'ı tercih edin.',
    icon: '🎵',
    packages: [
      {
        id: '9391',
        name: 'TikTok Takipçi [ 30 Gün Garantili ]',
        amount: '10 - 1.000.000 Takipçi',
        price: '300₺ / 1K',
        serviceId: '9391',
        min: 10,
        max: 1000000,
        avgTime: '7 dakika',
        features: ['30 Gün Garantili ♻️', 'Yüksek Kaliteli ve Gerçek Hesaplar', 'Günlük 100K'],
        category: 'follower',
      },
      
      {
        id: '9395',
        name: 'TikTok Beğeni [ 30 Gün Garantili ]',
        amount: '10 - 10.000.000 Beğeni',
        price: '100₺ / 1K',
        serviceId: '9395',
        min: 10,
        max: 10000000,
        avgTime: '31 dakika',
        features: ['30 Gün Garantili ♻️', 'Yüksek Kaliteli ve Gerçek Profiller', 'Günlük 100K'],
        category: 'like',
      },
      
      
      {
        id: '8247',
        name: 'TikTok Türk Beğeni',
        amount: '10 - 20.000 Beğeni',
        price: '150₺ / 1K',
        serviceId: '8247',
        min: 10,
        max: 20000,
        avgTime: '3 dakika',
        features: ['🇹🇷 Türk', 'Maksimum 20K', 'Süper Hızlı', 'Günlük 20K'],
        category: 'like',
      },
      {
        id: '9393',
        name: 'TikTok Video İzlenme',
        amount: '100 - 1.000.000.000 İzlenme',
        price: '4.6₺ / 1K',
        serviceId: '9393',
        min: 100,
        max: 1000000000,
        avgTime: '46 dakika',
        features: ['Sınırsız Maksimum Kapasite', 'Hızlı Başlangıç', 'Günlük 10M'],
        category: 'view',
      },
      
      
      {
        id: '5965',
        name: 'TikTok Kadın Etkileşim Paketi [ 5 Adet ]',
        amount: '1 Adet',
        price: '150₺',
        serviceId: '5965',
        min: 1,
        max: 1,
        avgTime: '1 saat 14 dakika',
        features: ['Kadın Kullanıcılar', 'İzle + Beğen + Yorum', '5 Adet'],
        category: 'engagement',
      },
      {
        id: '5971',
        name: 'TikTok Erkek Etkileşim Paketi [ 5 Adet ]',
        amount: '1 Adet',
        price: '150₺',
        serviceId: '5971',
        min: 1,
        max: 1,
        avgTime: '1 saat 44 dakika',
        features: ['Erkek Kullanıcılar', 'İzle + Beğen + Yorum', '5 Adet'],
        category: 'engagement',
      },
      {
        id: '3785-5',
        name: 'TikTok Yorum [ %100 Aktif Türk ] - 5 Adet',
        amount: '5 Yorum',
        price: '10₺',
        serviceId: '3785',
        min: 5,
        max: 5,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Premium Kalite', '5 Adet'],
        category: 'engagement',
      },
      {
        id: '3785-10',
        name: 'TikTok Yorum [ %100 Aktif Türk ] [Kampanya]',
        amount: '10 Yorum',
        price: '180₺',
        serviceId: '3785',
        min: 10,
        max: 10,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Premium Kalite', '10 Adet', '🔥 Kampanya'],
        category: 'engagement',
      },
      {
        id: '3785-40',
        name: 'TikTok Yorum [ %100 Aktif Türk ] - 40 Adet',
        amount: '40 Yorum',
        price: '80₺',
        serviceId: '3785',
        min: 40,
        max: 40,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Premium Kalite', '40 Adet'],
        category: 'engagement',
      },
      {
        id: '3785-50',
        name: 'TikTok Yorum [ %100 Aktif Türk ]',
        amount: '50 Yorum',
        price: '100₺',
        serviceId: '3785',
        min: 50,
        max: 50,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Premium Kalite', '50 Adet'],
        category: 'engagement',
      },
      {
        id: '3785-70',
        name: 'TikTok Yorum [ %100 Aktif Türk ] - 70 Adet',
        amount: '70 Yorum',
        price: '140₺',
        serviceId: '3785',
        min: 70,
        max: 70,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Premium Kalite', '70 Adet'],
        category: 'engagement',
      },
      {
        id: '3785-80',
        name: 'TikTok Yorum [ %100 Aktif Türk ]',
        amount: '80 Yorum',
        price: '160₺',
        serviceId: '3785',
        min: 80,
        max: 80,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Premium Kalite', '80 Adet'],
        category: 'engagement',
      },
      {
        id: '3785-100',
        name: 'TikTok Yorum [ %100 Aktif Türk ] - 100 Adet',
        amount: '100 Yorum',
        price: '200₺',
        serviceId: '3785',
        min: 100,
        max: 100,
        avgTime: '0 - 2 saat',
        features: ['%100 Aktif Türk 🇹🇷', 'Premium Kalite', '100 Adet'],
        category: 'engagement',
      },
      {
        id: '3951-50',
        name: 'TikTok Paylaşım',
        amount: '50 Paylaşım',
        price: '1₺',
        serviceId: '3951',
        min: 50,
        max: 50,
        avgTime: '28 dakika',
        features: ['Maksimum 1M', 'Hızlı Teslimat', '50 Adet'],
        category: 'engagement',
      },
      {
        id: '3951-100',
        name: 'TikTok Paylaşım - 100 Adet',
        amount: '100 Paylaşım',
        price: '2₺',
        serviceId: '3951',
        min: 100,
        max: 100,
        avgTime: '28 dakika',
        features: ['Maksimum 1M', 'Hızlı Teslimat', '100 Adet'],
        category: 'engagement',
      },
      {
        id: '3951-250',
        name: 'TikTok Paylaşım - 250 Adet',
        amount: '250 Paylaşım',
        price: '5₺',
        serviceId: '3951',
        min: 250,
        max: 250,
        avgTime: '28 dakika',
        features: ['Maksimum 1M', 'Hızlı Teslimat', '250 Adet'],
        category: 'engagement',
      },
      {
        id: '3951-500',
        name: 'TikTok Paylaşım - 500 Adet',
        amount: '500 Paylaşım',
        price: '10₺',
        serviceId: '3951',
        min: 500,
        max: 500,
        avgTime: '28 dakika',
        features: ['Maksimum 1M', 'Hızlı Teslimat', '500 Adet'],
        category: 'engagement',
      },
      {
        id: '3951-750',
        name: 'TikTok Paylaşım',
        amount: '750 Paylaşım',
        price: '15₺',
        serviceId: '3951',
        min: 750,
        max: 750,
        avgTime: '28 dakika',
        features: ['Maksimum 1M', 'Hızlı Teslimat', '750 Adet'],
        category: 'engagement',
      },
      {
        id: '3951-1000',
        name: 'TikTok Paylaşım - 1000 Adet',
        amount: '1000 Paylaşım',
        price: '20₺',
        serviceId: '3951',
        min: 1000,
        max: 1000,
        avgTime: '28 dakika',
        features: ['Maksimum 1M', 'Hızlı Teslimat', '1000 Adet'],
        category: 'engagement',
      },
      {
        id: '9201',
        name: 'TikTok Canlı Yayın İzlenme [ 30 Dakika | Maksimum 100K ]',
        amount: '100 Kişi',
        price: '30₺',
        serviceId: '9201',
        min: 100,
        max: 100,
        avgTime: '36 dakika',
        features: ['Canlı Yayın', '30 Dakika', 'Maksimum 100K', '100 Kişi Sabit'],
        category: 'view',
      },
      {
        id: '9181',
        name: 'TikTok Canlı Yayın İzlenme [ 60 Dakika | Maksimum 100K ]',
        amount: '100 Kişi',
        price: '190₺',
        serviceId: '9181',
        min: 100,
        max: 100,
        avgTime: '1 dakika',
        features: ['Canlı Yayın', '60 Dakika', 'Maksimum 100K', '100 Kişi Sabit'],
        category: 'view',
      },
      {
        id: '9237',
        name: 'TikTok Canlı Yayın İzlenme [ 90 Dakika | Maksimum 100K ]',
        amount: '100 Kişi',
        price: '285₺',
        serviceId: '9237',
        min: 100,
        max: 100,
        avgTime: 'Yeni Hizmet',
        features: ['Canlı Yayın', '90 Dakika', 'Maksimum 100K', '100 Kişi Sabit'],
        category: 'view',
      },
      {
        id: '9190',
        name: 'TikTok Canlı Yayın İzlenme [ 120 Dakika | Maksimum 100K ]',
        amount: '100 Kişi',
        price: '380₺',
        serviceId: '9190',
        min: 100,
        max: 100,
        avgTime: '1 dakika',
        features: ['Canlı Yayın', '120 Dakika', 'Maksimum 100K', '100 Kişi Sabit'],
        category: 'view',
      },
     
    ],
  },
  {
    id: 'twitter',
    name: 'Twitter (X)',
    description: 'Twitter hesabınızı büyütün ve tweetlerinizin etkileşimini artırın. Güvenilir ve hızlı çözümler için subjective\'ı tercih edin.',
    icon: '🐦',
    packages: [
      {
        id: '9342',
        name: 'Twitter Takipçi [ 30 Gün Garantili ]',
        amount: '100 - 50.000 Takipçi',
        price: '450₺ / 1K',
        serviceId: '9342',
        min: 100,
        max: 50000,
        avgTime: '15 saat 53 dakika',
        features: ['30 Gün Garantili ♻️', 'Yüksek Kaliteli Kullanıcılar', 'Günlük 10K'],
        category: 'follower',
      },
      
      {
        id: '9293',
        name: 'Twitter Türk Tweet Görüntülenme',
        amount: '100 - 50.000.000 Görüntülenme',
        price: '50₺ / 1K',
        serviceId: '9293',
        min: 100,
        max: 50000000,
        avgTime: '2 dakika',
        features: ['%100 Türk 🇹🇷', 'Anlık Başlar', 'Maksimum 50M'],
        category: 'view',
      },
      {
        id: '9256',
        name: 'Twitter Organik Takipçi',
        amount: '5 - 2.000 Takipçi',
        price: '2000₺ / 1K',
        serviceId: '9256',
        min: 5,
        max: 2000,
        avgTime: '13 saat 16 dakika',
        features: ['100% Organik', 'Maksimum 2K', 'Yüksek Kalite'],
        category: 'follower',
      },
      {
        id: '9257',
        name: 'Twitter Organik Retweet',
        amount: '1 - 2.000 Retweet',
        price: '200₺ / 1K',
        serviceId: '9257',
        min: 1,
        max: 2000,
        avgTime: '1 saat 14 dakika',
        features: ['100% Organik', 'Maksimum 2K', 'Yüksek Kalite'],
        category: 'engagement',
      },
      {
        id: '9258',
        name: 'Twitter Organik Beğeni',
        amount: '5 - 3.000 Beğeni',
        price: '180₺ / 1K',
        serviceId: '9258',
        min: 5,
        max: 3000,
        avgTime: '5 saat 2 dakika',
        features: ['100% Organik', 'Maksimum 3K', 'Günlük Hız 3K'],
        category: 'like',
      },
      {
        id: '9183',
        name: 'Twitter Canlı Yayın İzlenme [ 15 Dakika ]',
        amount: '50 - 200.000 İzlenme',
        price: '200₺ / 1K',
        serviceId: '9183',
        min: 50,
        max: 200000,
        avgTime: 'Yeni Hizmet',
        features: ['Canlı Yayın', '15 Dakika', 'Anlık Başlar'],
        category: 'view',
      },
      {
        id: '9184',
        name: 'Twitter Canlı Yayın İzlenme [ 30 Dakika ]',
        amount: '10 - 200.000 İzlenme',
        price: '450₺ / 1K',
        serviceId: '9184',
        min: 10,
        max: 200000,
        avgTime: 'Yeni Hizmet',
        features: ['Canlı Yayın', '30 Dakika', 'Anlık Başlar'],
        category: 'view',
      },
    ],
  },
  {
    id: 'twitch',
    name: 'Twitch',
    description: 'Twitch kanalınızı büyütün ve canlı yayınlarınızın izlenme sayısını artırın. Güvenilir ve hızlı çözümler için subjective\'ı tercih edin.',
    icon: '🎮',
    packages: [
      {
        id: '3376',
        name: 'Twitch Kanal İzlenmeleri [Maksimum 100M]',
        amount: '1.000 - 100.000.000 İzlenme',
        price: '149₺ / 1K',
        serviceId: '3376',
        min: 1000,
        max: 100000000,
        avgTime: '0 - 24 saat',
        features: ['Maksimum 100M', 'Hızlı Başlangıç', 'Yüksek Kalite'],
        category: 'view',
      },
      
      {
        id: '2714',
        name: 'Twitch Canlı Yayın İzlenme 30 Dakika [Maksimum 1K]',
        amount: '100 - 1.000 İzlenme',
        price: '500₺ / 1K',
        serviceId: '2714',
        min: 100,
        max: 1000,
        avgTime: 'Yeni Hizmet',
        features: ['Canlı Yayın', '30 Dakika', 'Maksimum 1K', 'Yeni Hizmet'],
        category: 'view',
      },
      {
        id: '8603',
        name: 'Twitch Followers [Auto Refill 30 days][High Quality][Instant Start - 5K/Day]',
        amount: '100 - 500.000 Takipçi',
        price: '105₺ / 1K',
        serviceId: '8603',
        min: 100,
        max: 500000,
        avgTime: 'Yeni Hizmet',
        features: ['30 Gün Otomatik Telafi ♻️', 'Yüksek Kalite', 'Anlık Başlangıç', 'Günlük 5K', 'Yeni Hizmet'],
        category: 'follower',
      },
      {
        id: '8604',
        name: '🇹🇷 Twitch Followers [Turkey][Auto Refill 30 days][High Quality][Instant Start - 5K/Day]',
        amount: '100 - 500.000 Takipçi',
        price: '135₺ / 1K',
        serviceId: '8604',
        min: 100,
        max: 500000,
        avgTime: 'Yeni Hizmet',
        features: ['%100 Türk 🇹🇷', '30 Gün Otomatik Telafi ♻️', 'Yüksek Kalite', 'Anlık Başlangıç', 'Günlük 5K', 'Yeni Hizmet'],
        category: 'follower',
      },
    ],
  },
]

// Paket fiyatlarını hesapla (1K fiyatından)
export function calculatePackagePrice(pricePer1K: string, amount: number): string {
  const numericPrice = parseFloat(pricePer1K.replace(/[^\d,]/g, '').replace(',', '.'))
  const totalPrice = (numericPrice * amount) / 1000
  return Math.round(totalPrice).toString() + '₺'
}

// Paket miktarlarını oluştur (min-max arası)
export function generatePackageAmounts(min: number, max: number): Array<{ amount: number; price: string }> {
  const amounts: number[] = []
  
  // Küçük paketler
  if (min <= 50) amounts.push(50)
  if (min <= 100) amounts.push(100)
  if (min <= 250) amounts.push(250)
  if (min <= 500) amounts.push(500)
  if (min <= 750) amounts.push(750)
  if (min <= 1000) amounts.push(1000)
  
  // Orta paketler
  if (min <= 2500 && max >= 2500) amounts.push(2500)
  if (min <= 5000 && max >= 5000) amounts.push(5000)
  if (min <= 7500 && max >= 7500) amounts.push(7500)
  if (min <= 10000 && max >= 10000) amounts.push(10000)
  
  // Büyük paketler
  if (min <= 25000 && max >= 25000) amounts.push(25000)
  if (min <= 50000 && max >= 50000) amounts.push(50000)
  if (min <= 75000 && max >= 75000) amounts.push(75000)
  if (min <= 100000 && max >= 100000) amounts.push(100000)
  if (min <= 250000 && max >= 250000) amounts.push(250000)
  if (min <= 500000 && max >= 500000) amounts.push(500000)
  if (min <= 1000000 && max >= 1000000) amounts.push(1000000)
  
  return amounts.filter(a => a >= min && a <= max).map(amount => ({
    amount,
    price: calculatePackagePrice('53,28₺ / 1K', amount), // Bu dinamik olmalı
  }))
}
